### ISSUE TITLE
error: ‘Monitor’ has no member named ‘clients’

### ISSUE THREAD

**Issue by shivangp76** [mhdzli/dwm-single-tagset-6.2#1]
After applying the dwm-single-tagset-6.2.diff and attempting to rebuild dwm, I got the following error:
```
$ make install
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA dwm.c
dwm.c: In function ‘drawbar’:
dwm.c:774:12: error: ‘Monitor’ has no member named ‘clients’
  774 |  for (c = m->clients; c; c = c->next) {
      |            ^~
make: *** [Makefile:18: dwm.o] Error 1
```

**Comment by mhdzli** [comment]
@shivangp76 
Witch version of dwm did you use?

**Comment by shivangp76** [comment]
6.2

**Comment by mhdzli** [comment]
@shivangp76 
Did you apply other patches before single-tagset?

**Comment by shivangp76** [comment]
Nope, I did not apply any other patches.

**Comment by mhdzli** [comment]
Apparently you have `for (c = m->clients; c; c = c->next) {` somewhere in your `dwm.c` if the you apply this patch correctly it should change to `for (c = m->cl->clients; c; c = c->next) {`
Did you use git apply for that?

**Comment by mhdzli** [comment]
Watch [this video](https://lbry.tv/@mzeinali:c/dmenupatches:7) on my lbry channel.

**Comment by mhdzli** [comment]
@shivangp76 

Watch [this video](https://lbry.tv/@mzeinali:c/dmenupatches:7) on my lbry channel.

**Comment by mhdzli** [comment]
@shivangp76 
Apparently you have `for (c = m->clients; c; c = c->next) {` somewhere in your `dwm.c` if you apply this patch correctly it should change to `for (c = m->cl->clients; c; c = c->next) {`
Did you use git apply for that?

**Comment by shivangp76** [comment]
I solved it. It turns out when I cloned dwm from the official suckless
repo, there were some changes to the code (even though it was still version
6.2) which created errors when applying the patch. To fix this, I just
downloaded the tarball from their website and then applied the patch. Thank
you for the help!

**Comment by mhdzli** [comment]
@shivangp76 
Great. Happy to hear that and your welcome!
