### ISSUE TITLE
Navigation. I think

### ISSUE THREAD

**Issue by DenisMutinda** [mhdzli/dwm-single-tagset-6.2#2]
Hello and great job on porting this patch to the latest dwm 6.2

After applying the patch on a vanilla install of dwm 6.2 whenever I use Mod+Shift+(1-9) to move a window, say Alacritty, to another tag and then switch to that tag( Mod+(1-9)), the application is 'minimized' - I can see the name on the status bar but the window is not visible. I have to do something for the application window to become visible e.g spawn another terminal then kill the new terminal so that I am left with the old one. 

Other than that, good job and kudos.

**Comment by ZaheenJ** [comment]
+1 Same thing here. I know nothing about programming though so I can't really fix it, but if this is fixed dwm will finally be the perfect wm for me!

**Comment by mhdzli** [comment]
@DenisMutinda
@ZaheenJ  
Thanks. I'll look into that at the earliest possible opportunity.

**Comment by sillen102** [comment]
I have the same issue. The problem is that when you switch to a tag the old is still active. For instance if I have a window open on the tag I'm switching from I can still interact with that window.

What method is being called when switching tags? I think it just needs to call restack or something. Because as soon as you do something on the tag you switched to, such as open a terminal it starts working as normal.

**Comment by mhdzli** [comment]
@sillen102 
Thank you. That was helpful.🙏
Sorry I will look into that. I'm not using dwm right now (contributing to a wayland compositor and I  am focused on that project also using swaywm🤪)
But I miss dwm  so hopefully I'll manage my work to find some free time in a few days. 😁

**Comment by sillen102** [comment]
I do have some patches and manual fixes on my build but if you would like to see exactly what I'm experiencing you can checkout my build. The single tag set patch is in a branch (I usually test patches out on a separate branch and then merge them).
https://github.com/sillen102/dwm/tree/single-tag-set

**Comment by sillen102** [comment]
I think I might have found where the issue is. Will test it later when I get back from work.

The problem I think are these lines in attachclients:
```
if (rmons)
	for (tm = mons; tm; tm = tm->next)
		if(tm != m)
			arrange(tm);
```
I believe that rmons is false when getting here? And therefore arrange isn't being called?

This is what the diff does to the view function:
```
-	arrange(selmon);
+	attachclients(selmon);
```
And so previously the arrange was always called in the end but now in the patch it's been moved to the attachclients function and it seems to not get called. And the only reason I can think of why is that rmons is always False?

I have only tried the patch when running in laptop mode (it has to work for one screen only as well as multimonitors anyway!). Don't know if that's why it isn't working properly for me at least?

Edit: As I look more into the diff I believe that the fix might be to just add a arrange(selmon) after the attachclients(selmon) in the view function. In the spawn function in the diff I see this:
```
Monitor *m;
+	unsigned int newtags;
+	if (selmon->sel && arg->ui & TAGMASK) {
+		newtags = arg->ui & TAGMASK;
+		for (m = mons; m; m = m->next)
+			/* if tag is visible on another monitor, move client to the new monitor */
+			if (m != selmon && m->tagset[m->seltags] & newtags) {
+				/* prevent moving client to all tags (MODKEY-Shift-0) when multiple monitors are connected */
+				if(newtags & selmon->tagset[selmon->seltags])
+					return;
+				selmon->sel->tags = newtags;
+				selmon->sel->mon = m;
+				arrange(m);
+				break;
+			}
+		/* workaround in case just one monitor is connected */
+
 		selmon->sel->tags = arg->ui & TAGMASK;
 		focus(NULL);
 		arrange(selmon);
```
The comment about the workaround is what catches my eye and that it has a call to arrange(selmon) at the end. That is probably why things start working normally after I spawn a new window after the switch. Like I said, will test it later tonight.

**Comment by sillen102** [comment]
I can confirm that adding arrange(selmon) after attachclients(selmon) in the view function fixed the issue for me. However I'm wondering if this means that it will be arranged twice in succession in some cases? Perhaps I could remove the if(rmons) statement in the attachclients function?

**Comment by sillen102** [comment]
I take that back. It did not work when I plugged in a second monitor...

**Comment by sillen102** [comment]
I now added this (code below) and it seems to work until I select a tag that is on the other monitor. Then the glitching out begins. It's as if the windows are not attached to a tag but to a monitor. So when I select that tag the windows are not moved over to the selected monitor with the tag.

Instead I get an empty tag and the other monitor becomes unresponsive (I can't switch tag on it). If I spawn a new window it will spawn on the monitor where the tag I tried to move to was. It's very strange!

I'm also using the pertag patch. Could it be the reason for this behaviour?

```
void
attachclients(Monitor *m)
{
    /* attach clients to the specified monitor */
    Monitor *tm;
    Client *c;
    unsigned int utags = 0;
    Bool rmons = False;
    if(!m)
       return;

    /* collect information about the tags in use */
    for (tm = mons; tm; tm = tm->next)
        if(tm != m)
           utags |= tm->tagset[tm->seltags];

    for (c = m->cl->clients; c; c = c->next)
        if(ISVISIBLE(c, m)) {
           /* if client is also visible on other tags that are displayed on
            * other monitors, remove these tags */
           if(c->tags & utags) {
               c->tags = c->tags & m->tagset[m->seltags];
               rmons = True;
           }
           unfocus(c, True);
           c->mon = m;
        }

    if (rmons) {
        for (tm = mons; tm; tm = tm->next)
           if(tm != m)
               arrange(tm);
    } else {
        arrange(selmon);
    }
}
```

**Comment by sillen102** [comment]
It is not a problem with pertag. I removed the pertag patch and I still get this behaviour.

**Comment by sillen102** [comment]
And I just tried applying the patch to clean vanilla dwm and it doesn't work. I did apply it to the git version and not the official 6.2 version. Could this be the reason it's not working?

**Comment by volfyd** [comment]
I think that dwm-single_tagset-20160731-56a31dc.diff on https://dwm.suckless.org/patches/single_tagset/ displays the same bad behavior.

**Comment by anne-pc** [comment]
This is the reason I've switched to xmonad a couple months ago, the tagset behaviour on a three monitor setup is just annoying, so many screens, so little flexibility. would love to see this worked out but im afraid the resolution is out of the scope of this patch as is :(

**Comment by mhdzli** [comment]
@noobadmin 
I spent a few days working on it but couldn't find a proper way to solve this issue.
I'm using swaywm right now and working on a dwm like wm for wayland. 
I don't have a multi monitor set up right now, but I'll try a new way to handle the single tag set for dwm and if it works (which I'm pretty sure it should) I will update this repo.

**Comment by anne-pc** [comment]
I'm not really fluent in c and neither have read the source, so I'm not able to contribute at this point. However if it helps with debugging or lost window trouble, cycling layouts semms resolve the issue. So I'm thinking we either implement this functionality deeper to resolve this "It's as if the windows are not attached to a tag but to a monitor." or we emulate the former resolution in an elegant way if possible?

**Comment by sillen102** [comment]
Any updates?

**Comment by BrunoCooper17** [comment]
I was trying to make this patch work and I think I have found more about this problem. On the view method, the `selmon` variable changes before `attachclients(selmon)` was called. I'm pretty sure dwm changes `selmon` somewhere when the monitors get rearrenged (`updategeom` is one of my suspects). Right now i'm testing storing `selmon` in a local variable. I will come back if this works or if I find more info about it :smiley:

**Comment by BrunoCooper17** [comment]
I'm back and I think I figure it out :smiley:

I was wrong about `updategeom` being the method changing `selmon`, it was `focus` and there's one call just before `attachclients` at the end of the `view` method. Calling `attachclients` before the `focus(NULL)` seems to fix this issue.

My view method ended up like this:

```
void
view(const Arg *arg)
{
	Monitor *m;
	unsigned int newtagset = selmon->tagset[selmon->seltags ^ 1];
	if ((arg->ui & TAGMASK) == selmon->tagset[selmon->seltags])
		return;
	/* swap tags when trying to display a tag from another monitor */
	if (arg->ui & TAGMASK)
		newtagset = arg->ui & TAGMASK;
	for (m = mons; m; m = m->next)
		if (m != selmon && newtagset & m->tagset[m->seltags]) {
			/* prevent displaying all tags (MODKEY-0) when multiple monitors
			 * are connected */
			if (newtagset & selmon->tagset[selmon->seltags])
				return;
			m->sel = selmon->sel;
			m->seltags ^= 1;
			m->tagset[m->seltags] = selmon->tagset[selmon->seltags];
			attachclients(m);
			arrange(m);
			break;
		}
	selmon->seltags ^= 1; /* toggle sel tagset */
	if (arg->ui & TAGMASK)
		selmon->tagset[selmon->seltags] = arg->ui & TAGMASK;

        // Call attachclients and arrange before focus
	attachclients(selmon);
	arrange(selmon);
	focus(NULL);
}
```

The same applies to `toggleview`:

```
void
toggleview(const Arg *arg)
{
	Monitor *m;
	unsigned int newtagset = selmon->tagset[selmon->seltags] ^ (arg->ui & TAGMASK);

	if (newtagset) {
		/* prevent displaying the same tags on multiple monitors */
		for(m = mons; m; m = m->next)
			if(m != selmon && newtagset & m->tagset[m->seltags])
				return;
		selmon->tagset[selmon->seltags] = newtagset;

                // Call attachclients and arrange before focus
		attachclients(selmon);
		arrange(selmon);
		focus(NULL);

		unsigned int newtagset = selmon->tagset[selmon->seltags] ^ (arg->ui & TAGMASK);

		if (newtagset) {
			selmon->tagset[selmon->seltags] = newtagset;

                        // Call attachclients and arrange before focus
			attachclients(selmon);
			arrange(selmon);
			focus(NULL);
		}
	}
}
```

I will keep testing if this change solves the problem (so far it seems it does it).

**Comment by mhdzli** [comment]
@BrunoCooper17 
Looks good to me. Would you mind adding a PR? And also update the patch in [suckless website](https://dwm.suckless.org/patches/single_tagset/)

**Comment by BrunoCooper17** [comment]
No problem, give me a couple of hours and I will do it. If anyone else in this thread can help testing it just to confirm it's working it would be great.

**Comment by sillen102** [comment]
I can test.

**Comment by BrunoCooper17** [comment]
Thank you @sillen102

**Comment by mhdzli** [comment]
@BrunoCooper17 
Thanks and feel free to add yourself to the authors list in the suckless patch :D

**Comment by BrunoCooper17** [comment]
Thank you. One quick question... Do i keep the same name for the patch or do i upload a new one with the name dwm-singletag-20210623-67d76bd.diff? :thinking:

**Comment by mhdzli** [comment]
@BrunoCooper17 
You can make a patch based on the 6.2 release and update the single_tagset-6.2 diff file or make a patch based on the latest source code and make a new file.
