### ISSUE TITLE
Patch Failed

### ISSUE THREAD

**Issue by JingerJack** [mhdzli/dwm-single-tagset-6.2#4]
I am attempting to apply the latest version of single tagset ( dwm-single_tagset-20210623-67d76bd.diff ) to DWM 6.2 (from suckless's github repo), but I get this error
`jackson@jackson-desktop:~/dwm$ git apply dwm-single_tagset--20210623-67d76bd.diff
 `
`error: patch failed: dwm.c:838`
`error: dwm.c: patch does not apply`

I am very new to DWM but from what I have gathered the patch was created for a different version of DWM. I think this is the issue because the patch (dwm-single_tagset-6.2.diff) applies just fine to the 6.2 version of DWM from their website. 

Am I using the wrong version of DWM? and if so where can I get the version of DWM that will work with dwm-single_tagset-20210623-67d76bd.diff

Thanks

**Comment by mhdzli** [comment]
@JingerJack 
I just patched single-tagset to both dwm 6.2 and the latest git source without any errors. Did you patched bare dwm source code?

**Comment by mhdzli** [comment]
I didn't pull the latest commit before patching the single-tagset diff file.
The 838th line of `dwm.c` changed from `if (!selmon->sel || selmon->sel->isfullscreen)` to `if (!selmon->sel || (selmon->sel->isfullscreen && lockfullscreen))`.
So if you want to patch it to the latest commit you should edit [this line](https://github.com/mhdzli/dwm-single-tagset-6.2/blob/a605b20863479b9e7a077dd351e4cd052c921e0d/dwm-single-tagset-6.2.diff#L274) in the diff file.

**Comment by mhdzli** [comment]
@JingerJack 
Use [this patch file](https://github.com/mhdzli/dwm-single-tagset-6.2/blob/6726c00b7662d06411dd12c46b1aa513e0abe4a5/suckless-diff-format/dwm-single_tagset-20211115-a786211.diff) for the latest source code.
