### ISSUE TITLE
DWM-6.3 support

### ISSUE THREAD

**Issue by yanboyang713** [mhdzli/dwm-single-tagset-6.2#5]
Hello Guys,

Good day to you.

I am new to DWM and found this patch. 

Currently, I am using dwm-flexipatch, I have NOT found your guy's patch in dwm-flexipatch.

I am manually merging this patch to DWM-6.3, but unsuccessful.

May I ask, does DWM-6.3 support this patch?

There are three functions, I am no ideas how to apply them to DWM-6.3. Do you guys have some guidelines to apply to this patch? Thanks for your help.
1. spawn(const Arg *arg)
2. tile(Monitor *m)
3. updatewmhints(Client *c)

I am new to DWM, do you guys know some of the tutorials to learn DWM for beginners? Thanks

**Comment by ghost** [comment]
Waiting on this one, still

**Comment by mhdzli** [comment]
[Here](https://github.com/mhdzli/dwm-single-tagset/blob/master/suckless-diff-format/dwm-single_tagset-6.5.diff) is the diff file for DWM 6.5

**Comment by mhdzli** [comment]
[Here](https://github.com/mhdzli/dwm-single-tagset/blob/master/suckless-diff-format/dwm-single_tagset-6.5.diff) is the diff file for DWM 6.5
