### ISSUE TITLE
dwm-6.4 is supported! but the .diff file is broken

### ISSUE THREAD

**Issue by kigel** [mhdzli/dwm-single-tagset-6.2#6]
Hello contributers! i really like this patch because i came from Qtile which uses the same logic in the sense of the tagset/workspaces are the same for all monitors, so i thank you for making this patch.

Altough the patch it self still works, the .diff file is broken and i had to manually apply this patch.

so it would be nice if you updated the .diff file for dwm-6.4 :)

**Comment by mhdzli** [comment]
[Here](https://github.com/mhdzli/dwm-single-tagset/blob/master/suckless-diff-format/dwm-single_tagset-6.5.diff) is the diff file for DWM 6.5
